version: '3.8'

services:
  tokenizer:
    build: 
      context: .
      dockerfile: Dockerfile
    # env_file:
    #   - ./deployment/.env
    stdin_open: true # keep STDIN open and allocate a TTY, needed for the interactive TUI
    tty: true
    # Mounting file without having to rebuild the container
    volumes:
      - .:/app # mount all the app
      - /app/deployment/node_modules
      - /app/.venv
