version: '3.8'

services:
  tokenizer:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: tokenizer_app
    env_file:
      - ./deployment/.env
    stdin_open: true
    tty: true
    # Mounting file without having to rebuild the container
    volumes:
      - .:/app # mount all the app
      - /app/deployment/node_modules
      - /app/.venv
